import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import path from 'node:path';
import fs from 'node:fs/promises';
import { MemoryJobSink, fixtureExists, fixtureRepoPath, newJobId } from './helpers';

/**
 * End-to-end integration: the ESM/CJS fixture.
 *
 * This is the canonical offline path — no registry, no network, no toolchain
 * beyond Node itself — so it must pass on any machine that can run Revive.
 */

let runJob: typeof import('../src/engine/orchestrator').runJob;
let dataDir: string;

beforeAll(async () => {
  dataDir = path.resolve(__dirname, '..', '.revive-test', 'esm');
  await fs.rm(dataDir, { recursive: true, force: true });
  await fs.mkdir(dataDir, { recursive: true });
  process.env.REVIVE_DATA_DIR = dataDir;
  process.env.REVIVE_STEP_TIMEOUT_MS = '120000';

  // Import after the env is set so config picks up the test data dir.
  ({ runJob } = await import('../src/engine/orchestrator'));
});

afterAll(async () => {
  await fs.rm(dataDir, { recursive: true, force: true, maxRetries: 3, retryDelay: 300 });
});

describe('node-half-migration fixture', () => {
  it('is built', async () => {
    expect(await fixtureExists('node-half-migration')).toBe(true);
  });

  it('detects, diagnoses, repairs and verifies end to end', async () => {
    const sink = new MemoryJobSink();
    const controller = new AbortController();

    const result = await runJob({
      jobId: newJobId(),
      repoUrl: 'fixture://revive/node-half-migration/tiny-metrics',
      localPath: fixtureRepoPath('node-half-migration'),
      sink,
      signal: controller.signal,
    });

    // --- Phase progression -------------------------------------------------
    expect(sink.phases).toContain('analyze');
    expect(sink.phases).toContain('reconstruct');
    expect(sink.phases).toContain('baseline');

    // --- Detection ---------------------------------------------------------
    const detection = sink.state.detection as any;
    expect(detection.language).toBe('node');
    expect(detection.packageManager).toBe('npm');
    // The package claims ESM but the source is CommonJS: detection must report
    // the conflict rather than believing the declaration.
    expect(detection.moduleSystem).toBe('mixed');

    // --- Environment archaeology -------------------------------------------
    const env = sink.state.originalEnv as any;
    expect(env.runtime).toBe('node');
    // .nvmrc pins 10.16.3 — the strongest possible evidence.
    expect(env.runtimeVersion).toBe('10.16.3');
    expect(env.evidence.some((e: any) => e.source === '.nvmrc')).toBe(true);
    expect(env.confidence).toBeGreaterThanOrEqual(80);

    // --- Baseline must genuinely fail --------------------------------------
    const baseline = sink.state.baseline as any;
    expect(baseline.overall).not.toBe('working');

    // --- Diagnosis ---------------------------------------------------------
    const diagnoses = sink.state.diagnosis as any[];
    expect(diagnoses.length).toBeGreaterThan(0);
    expect(diagnoses.some((d) => d.category === 'module-system')).toBe(true);

    // --- Repair and verification -------------------------------------------
    const final = sink.state.finalResult as any;
    expect(final.score).toBeGreaterThan(baseline.score);
    expect(result.status).toBe('succeeded');
    expect(final.overall).toBe('working');

    // The repair must be the minimal one, not a rewrite.
    const repairs = (sink.state.repairs as any[]).filter((r) => !r.rolledBack);
    expect(repairs.some((r) => r.id === 'esm-remove-type-module')).toBe(true);

    // --- Artifacts ---------------------------------------------------------
    const changed = sink.state.changedFiles as any[];
    expect(changed.some((f) => f.path === 'package.json')).toBe(true);
    expect(typeof sink.state.diffText).toBe('string');
    expect(sink.state.diffText as string).toContain('"type": "module"');

    // Files generated by running the project (npm's lockfile) are not repairs
    // and must not appear in the patch.
    expect(changed.some((f) => f.path === 'package-lock.json')).toBe(false);
    expect(sink.logs.some((l) => l.message.includes('Left out'))).toBe(true);

    // Only package.json should change — behaviour must be preserved.
    const sourceChanges = changed.filter((f) => f.path.startsWith('src/'));
    expect(sourceChanges).toHaveLength(0);
  });
});
